### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: timeouts

### ISSUE THREAD

**Issue by SamosHaven** [hadojae/DATA#24]
Hi,

OS: Ubuntu

So when i try and use bucklegripper on a URL (URL is in links.txt) i get this error message in response:
sudo python bucklegripper.py -r links.txt
[sudo] password for user: 

.: BUCKLEGRIPPER v0.1 https://github.com/hadojae/DATA :.

[+] Beginning processing of links.txt

[+] Processing http://gateway-taxid-38573.gucaoa.com/returnGB77GS183R
Traceback (most recent call last):
  File "bucklegripper.py", line 320, in <module>
    main()
  File "bucklegripper.py", line 315, in main
    mainloop(full, headers, user_agent, source)
  File "bucklegripper.py", line 228, in mainloop
    selenium_result = do_selenium(full, user_agent, domain, source)
  File "bucklegripper.py", line 65, in do_selenium
    browser.set_page_load_timeout(15)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 818, in set_page_load_timeout
    'type': 'page load'})
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: timeouts

I have used bucklegripper several times in the past to scan other URLs but this one always pops up with this error.

Anyone know of a fix?
Edit: DONT visit the webpage that I have tried scanning. This is a known phishing site.

**Comment by hadojae** [comment]
jae@elasticsearch:~/phish$ python bucklegripper.py -r test324.txt

.: BUCKLEGRIPPER v0.1 https://github.com/hadojae/DATA :.

[+] Beginning processing of test324.txt

[+] Processing http://gateway-taxid-38573.gucaoa.com/returnGB77GS183R
  [+] Screencapped http://gateway-taxid-38573.gucaoa.com/returnGB77GS183R as 20171020-073532-bucklegripper-gateway-taxid-38573.gucaoa.com.png

[+] Finished processing test324.txt

What version of selenium/firefox/geckodriver are you on? Maybe try updating those to latest. Also check to make sure you have the most recent version of bucklegripper.

**Comment by SamosHaven** [comment]
Reninstalled selenium and fixed it. Cheers
